apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eks-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/BBrucelee2002/argo-appset-demo.git  # 👈 YOUR REPO HERE
      revision: HEAD
      directories:
      - path: apps/*  # 👈 Looks for apps in "apps/" folder
  
  template:
    metadata:
      name: '{{path.basename}}'  # Names the app after the folder (e.g., "guestbook")
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'    # Uses the same Git repo
        targetRevision: HEAD
        path: '{{path}}'          # Path to app (e.g., "apps/guestbook")
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'  # Creates a namespace matching the app name
      syncPolicy:
        automated: {}  # Auto-syncs changes