apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-demo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/your-username/argo-appset-demo.git
      revision: HEAD
      directories:
      - path: apps/*
  
  template:
    metadata:
      name: '{{path.basename}}'  # Uses folder name (e.g., "guestbook")
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true